-- No accounts or credentials are seeded automatically.
-- Register an account with a unique strong password through /api/auth/register.
-- After verifying its owner and numeric ID, an operator may explicitly grant ADMIN:
-- UPDATE `user` SET `type` = 'ADMIN' WHERE `id` = <verified_user_id>;
-- Existing deployments must replace previously seeded credentials before exposure.
