package com.web.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.time.LocalDateTime;

/**
 * 用户提及实体类
 * 用于支持在消息中提及其他用户
 */
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class UserMention extends BaseEntity {

    /**
     * 消息ID
     */
    private Long messageId;

    /**
     * 提及者ID
     */
    private Long mentionerId;

    /**
     * 提及者用户名
     */
    private String mentionerUsername;

    /**
     * 被提及用户ID
     */
    private Long mentionedUserId;

    /**
     * 被提及用户名
     */
    private String mentionedUsername;

    /**
     * 提及文本（包含@符号的完整提及）
     */
    private String mentionText;

    /**
     * 提及在消息中的起始位置
     */
    private Integer startPosition;

  /**
     * 提及在消息中的结束位置
     */
    private Integer endPosition;

    /**
     * 提及状态（pending, delivered, read）
     */
    private String status;

    /**
     * 提及类型（reply, mention, reply_all）
     */
    private String mentionType;

     /**
     * 是否已读
     */
    private Boolean isRead;

    /**
     * 读取时间
     */
    private LocalDateTime readAt;

    /**
     * 是否自动提及（如@all）
     */
    private Boolean isAutoGenerated;

    /**
     * 额外元数据（JSON格式）
     */
    private String metadata;

    public UserMention() {
        this.status = "pending";
        this.isRead = false;
        this.isAutoGenerated = false;
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    public UserMention(Long messageId, Long mentionerId, Long mentionedUserId, String mentionText) {
        this();
        this.messageId = messageId;
        this.mentionerId = mentionerId;
        this.mentionedUserId = mentionedUserId;
        this.mentionText = mentionText;
    }

    /**
     * 提及状态枚举
     */
    public static class Status {
        public static final String PENDING = "pending";
        public static final String DELIVERED = "delivered";
        public static final String READ = "read";
    }

    /**
     * 提及类型枚举
     */
    public static class MentionType {
        public static final String MENTION = "mention";
        public static final String REPLY = "reply";
        public static final String REPLY_ALL = "reply_all";
    }

    /**
     * 标记为已读
     */
    public void markAsRead() {
        this.isRead = true;
        this.readAt = LocalDateTime.now();
        this.status = Status.READ;
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * 标记为已送达
     */
    public void markAsDelivered() {
        this.status = Status.DELIVERED;
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * 检查提及是否有效
     */
    public boolean isValid() {
        return messageId != null && mentionerId != null && mentionedUserId != null
                && mentionText != null && !mentionText.trim().isEmpty();
    }

    /**
     * 检查是否是自动提及
     */
    public boolean isSystemMention() {
        return isAutoGenerated || MentionType.REPLY_ALL.equals(mentionType);
    }
}