spring:
  profiles:
    active: dev # Default to dev environment
    # 可用的配置文件：dev, prod
    # 生产环境启动命令：java -jar app.jar --spring.profiles.active=prod

  # MySQL数据库配置（开发环境）
  datasource:
    url: jdbc:mysql://localhost:3306/weeb?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useServerPrepStmts=true&cachePrepStmts=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root  # 开发环境默认用户名
    password: 1234  # 开发环境默认密码
    hikari:
      pool-name: WeebDevHikariPool
      minimum-idle: 5  # 最小空闲连接数
      maximum-pool-size: 20  # 最大连接数
      connection-timeout: 30000  # 连接超时时间（毫秒）
      idle-timeout: 600000  # 空闲连接超时时间（毫秒）
      max-lifetime: 1800000  # 连接最大生命周期（毫秒）
      validation-timeout: 5000  # 验证超时时间（毫秒）
      leak-detection-threshold: 60000  # 泄露检测阈值（毫秒）
      connection-test-query: SELECT 1  # 连接测试查询

  # MyBatis-Plus配置
  mybatis-plus:
    mapper-locations: classpath*:/Mapper/*.xml
    type-aliases-package: com.web.model
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # Redis配置（已启用）
  # Redis服务已启动，监听端口：6379
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # Elasticsearch配置（强制使用HTTPS + SSL证书）
  elasticsearch:
    uris: https://localhost:9200
    username: elastic
    password: "123456"
    restclient:
      ssl:
        bundle: es-pem-bundle

weeb:
  password: sun55@kong # 群聊密码
  limit: 100 # 在线人数限制
  name: 233 # 群聊名称
  expires: 7 # 数据过期时间（天）
  upload:
    base-path: uploads # 本地文件上传基础路径

  # SSL Bundle配置（强制使用SSL证书）
  ssl:
    bundle:
      pem:
        es-pem-bundle:
          truststore:
            certificate: classpath:es/http_ca.crt

  # 可选：临时关闭 Reactive ES 自动装配，纯用阻塞式客户端即可
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchClientAutoConfiguration

  # Redis配置优化（已合并到上面的Redis配置中）
  # repositories.enabled已在上面配置


# JWT配置
jwt:
  secret: "6nN}V5m9A=QwP^2zDgFj@2025#Strong#Key#RotateMe" # 强随机秘钥
  expiration: 86400000 # JWT令牌有效期，默认为24小时（毫秒）