# 应用程序配置文件
server:
  port: 8080   # 服务器端口号

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weeb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC  # 数据库连接地址，数据库名称为 weeb
    username: root    # 数据库用户名
    password:     # 替换为实际的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver   # MySQL 驱动类
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml    # MyBatis 映射文件位置
  type-aliases-package: com.web.model     # 实体类包路径，可根据实际包结构调整

jwt:
  secret:
  expiration: 3600000   # JWT 过期时间（毫秒）

logging:
  level:
    root: INFO
    com.web: DEBUG # 设置为DEBUG以便看到更多日志信息

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

WEEB:
  password: sun55@kong #群聊密码
  limit: 100 #在线人数限制
  name: 233 #群聊名称
  expires: 7 #数据过期时间（天）
  doubao: #豆包
    api-key: apikey
    count-limit: 5 #次数限制,0-不限制
    length-limit: 50 #内容长度限制,0-不限制
    model: ep-20241231132608-lbm7g