// 常用表情符号数据
export default [
  { icon: '😀', name: 'grinning face', keywords: ['happy', 'smile'] },
  { icon: '😃', name: 'grinning face with big eyes', keywords: ['happy', 'smile'] },
  { icon: '😄', name: 'grinning face with smiling eyes', keywords: ['happy', 'smile'] },
  { icon: '😁', name: 'beaming face with smiling eyes', keywords: ['happy', 'smile'] },
  { icon: '😅', name: 'grinning face with sweat', keywords: ['sweat', 'smile'] },
  { icon: '😂', name: 'face with tears of joy', keywords: ['laugh', 'happy'] },
  { icon: '🤣', name: 'rolling on the floor laughing', keywords: ['laugh', 'happy'] },
  { icon: '😊', name: 'smiling face with smiling eyes', keywords: ['happy', 'smile'] },
  { icon: '😇', name: 'smiling face with halo', keywords: ['angel', 'innocent'] },
  { icon: '🙂', name: 'slightly smiling face', keywords: ['smile', 'happy'] },
  { icon: '😉', name: 'winking face', keywords: ['wink', 'happy'] },
  { icon: '😌', name: 'relieved face', keywords: ['relaxed', 'peaceful'] },
  { icon: '😍', name: 'heart eyes face', keywords: ['love', 'heart'] },
  { icon: '🥰', name: 'smiling face with hearts', keywords: ['love', 'happy'] },
  { icon: '😘', name: 'face blowing a kiss', keywords: ['kiss', 'love'] },
  { icon: '😗', name: 'kissing face', keywords: ['kiss', 'love'] },
  { icon: '😙', name: 'kissing face with smiling eyes', keywords: ['kiss', 'love'] },
  { icon: '😚', name: 'kissing face with closed eyes', keywords: ['kiss', 'love'] },
  { icon: '😋', name: 'face savoring food', keywords: ['yummy', 'food'] },
  { icon: '😛', name: 'face with tongue', keywords: ['silly', 'funny'] },
  { icon: '😜', name: 'winking face with tongue', keywords: ['silly', 'funny'] },
  { icon: '🤪', name: 'zany face', keywords: ['crazy', 'silly'] },
  { icon: '😝', name: 'squinting face with tongue', keywords: ['silly', 'funny'] },
  { icon: '🤗', name: 'hugging face', keywords: ['hug', 'love'] },
  { icon: '🤭', name: 'face with hand over mouth', keywords: ['surprise', 'secret'] },
  { icon: '🤫', name: 'shushing face', keywords: ['quiet', 'secret'] },
  { icon: '🤔', name: 'thinking face', keywords: ['thinking', 'ponder'] },
  { icon: '🤐', name: 'zipper-mouth face', keywords: ['silent', 'quiet'] },
  { icon: '🤨', name: 'face with raised eyebrow', keywords: ['skeptical', 'doubt'] },
  { icon: '😐', name: 'neutral face', keywords: ['neutral', 'blank'] },
  { icon: '😑', name: 'expressionless face', keywords: ['blank', 'neutral'] },
  { icon: '😶', name: 'face without mouth', keywords: ['silent', 'quiet'] },
  { icon: '😏', name: 'smirking face', keywords: ['smirk', 'confident'] },
  { icon: '😒', name: 'unamused face', keywords: ['annoyed', 'unimpressed'] },
  { icon: '🙄', name: 'face with rolling eyes', keywords: ['annoyed', 'sarcasm'] },
  { icon: '😬', name: 'grimacing face', keywords: ['awkward', 'nervous'] },
  { icon: '😮', name: 'face with open mouth', keywords: ['surprise', 'shock'] },
  { icon: '😯', name: 'hushed face', keywords: ['surprise', 'shock'] },
  { icon: '😲', name: 'astonished face', keywords: ['surprise', 'shock'] },
  { icon: '😳', name: 'flushed face', keywords: ['embarrassed', 'shy'] },
  { icon: '🥺', name: 'pleading face', keywords: ['puppy', 'pleading'] },
  { icon: '😢', name: 'crying face', keywords: ['sad', 'cry'] },
  { icon: '😭', name: 'loudly crying face', keywords: ['sad', 'cry'] },
  { icon: '😤', name: 'face with steam from nose', keywords: ['angry', 'mad'] },
  { icon: '😠', name: 'angry face', keywords: ['angry', 'mad'] },
  { icon: '😡', name: 'enraged face', keywords: ['angry', 'rage'] },
  { icon: '🤬', name: 'face with symbols on mouth', keywords: ['angry', 'swear'] },
  { icon: '🤯', name: 'exploding head', keywords: ['mind', 'blown'] },
  { icon: '😳', name: ' flushed face', keywords: ['embarrassed', 'shy'] },
  { icon: '🥵', name: 'hot face', keywords: ['hot', 'warm'] },
  { icon: '🥶', name: 'cold face', keywords: ['cold', 'freezing'] },
  { icon: '😱', name: 'face screaming in fear', keywords: ['fear', 'scream'] },
  { icon: '😨', name: 'fearful face', keywords: ['fear', 'scared'] },
  { icon: '😰', name: 'anxious face with sweat', keywords: ['anxious', 'nervous'] },
  { icon: '😥', name: 'sad but relieved face', keywords: ['relief', 'mixed'] },
  { icon: '😓', name: 'downcast face with sweat', keywords: ['sad', 'sweat'] },
  { icon: '🤗', name: 'hugging face', keywords: ['hug', 'love'] },
  { icon: '🤔', name: 'thinking face', keywords: ['thinking', 'ponder'] },
  { icon: '🤭', name: 'face with hand over mouth', keywords: ['surprise', 'secret'] },
  { icon: '🤫', name: 'shushing face', keywords: ['quiet', 'secret'] },
  { icon: '🤥', name: 'lying face', keywords: ['lie', 'dishonest'] },
  { icon: '😶', name: 'face without mouth', keywords: ['silent', 'quiet'] },
  { icon: '😐', name: 'neutral face', keywords: ['neutral', 'blank'] },
  { icon: '😑', name: 'expressionless face', keywords: ['blank', 'neutral'] },
  { icon: '😬', name: 'grimacing face', keywords: ['awkward', 'nervous'] },
  { icon: '🙄', name: 'face with rolling eyes', keywords: ['annoyed', 'sarcasm'] },
  { icon: '😯', name: 'hushed face', keywords: ['surprise', 'shock'] },
  { icon: '😦', name: 'frowning face with open mouth', keywords: ['worry', 'concern'] },
  { icon: '😧', name: 'anguished face', keywords: ['pain', 'anguish'] },
  { icon: '😮', name: 'face with open mouth', keywords: ['surprise', 'shock'] },
  { icon: '😲', name: 'astonished face', keywords: ['surprise', 'shock'] },
  { icon: '🥱', name: 'yawning face', keywords: ['yawn', 'tired'] },
  { icon: '😴', name: 'sleeping face', keywords: ['sleep', 'tired'] },
  { icon: '🤤', name: 'drooling face', keywords: ['drool', 'sleep'] },
  { icon: '😪', name: 'sleepy face', keywords: ['tired', 'sleepy'] },
  { icon: '😵', name: 'dizzy face', keywords: ['dizzy', 'confused'] },
  { icon: '🤐', name: 'zipper-mouth face', keywords: ['silent', 'quiet'] },
  { icon: '🥴', name: 'woozy face', keywords: ['drunk', 'dizzy'] },
  { icon: '🤢', name: 'nauseated face', keywords: ['sick', 'nausea'] },
  { icon: '🤮', name: 'vomiting face', keywords: ['sick', 'vomit'] },
  { icon: '🤧', name: 'sneezing face', keywords: ['sneeze', 'cold'] },
  { icon: '😷', name: 'face with medical mask', keywords: ['sick', 'mask'] },
  { icon: '🤒', name: 'face with thermometer', keywords: ['sick', 'fever'] },
  { icon: '🤕', name: 'face with head-bandage', keywords: ['injury', 'hurt'] },
  { icon: '🤑', name: 'money-mouth face', keywords: ['money', 'rich'] },
  { icon: '🤠', name: 'cowboy hat face', keywords: ['cowboy', 'hat'] },
  { icon: '😈', name: 'smiling face with horns', keywords: ['devil', 'evil'] },
  { icon: '👿', name: 'angry face with horns', keywords: ['devil', 'angry'] },
  { icon: '👹', name: 'japanese ogre', keywords: ['ogre', 'monster'] },
  { icon: '👺', name: 'japanese goblin', keywords: ['goblin', 'monster'] },
  { icon: '🤡', name: 'clown face', keywords: ['clown', 'funny'] },
  { icon: '💩', name: 'pile of poo', keywords: ['poop', 'shit'] },
  { icon: '👻', name: 'ghost', keywords: ['ghost', 'halloween'] },
  { icon: '💀', name: 'skull', keywords: ['death', 'skeleton'] },
  { icon: '☠️', name: 'skull and crossbones', keywords: ['danger', 'poison'] },
  { icon: '👽', name: 'alien', keywords: ['alien', 'ufo'] },
  { icon: '👾', name: 'alien monster', keywords: ['alien', 'monster'] },
  { icon: '🤖', name: 'robot face', keywords: ['robot', 'technology'] },
  { icon: '🎃', name: 'jack-o-lantern', keywords: ['halloween', 'pumpkin'] },
  { icon: '😺', name: 'grinning cat face', keywords: ['cat', 'happy'] },
  { icon: '😸', name: 'grinning cat face with smiling eyes', keywords: ['cat', 'happy'] },
  { icon: '😹', name: 'cat face with tears of joy', keywords: ['cat', 'laugh'] },
  { icon: '😻', name: 'smiling cat face with heart-eyes', keywords: ['cat', 'love'] },
  { icon: '😼', name: 'cat face with wry smile', keywords: ['cat', 'smirk'] },
  { icon: '😽', name: 'kissing cat face', keywords: ['cat', 'kiss'] },
  { icon: '🙀', name: 'weary cat face', keywords: ['cat', 'shock'] },
  { icon: '😿', name: 'crying cat face', keywords: ['cat', 'sad'] },
  { icon: '😾', name: 'pouting cat face', keywords: ['cat', 'angry'] },
  { icon: '🙈', name: 'see-no-evil monkey', keywords: ['monkey', 'see'] },
  { icon: '🙉', name: 'hear-no-evil monkey', keywords: ['monkey', 'hear'] },
  { icon: '🙊', name: 'speak-no-evil monkey', keywords: ['monkey', 'speak'] },
  { icon: '💋', name: 'kiss mark', keywords: ['kiss', 'love'] },
  { icon: '💌', name: 'love letter', keywords: ['love', 'letter'] },
  { icon: '💘', name: 'heart with arrow', keywords: ['love', 'heart'] },
  { icon: '💝', name: 'heart with ribbon', keywords: ['love', 'heart'] },
  { icon: '💖', name: 'sparkling heart', keywords: ['love', 'heart'] },
  { icon: '💗', name: 'growing heart', keywords: ['love', 'heart'] },
  { icon: '💓', name: 'beating heart', keywords: ['love', 'heart'] },
  { icon: '💞', name: 'revolving hearts', keywords: ['love', 'heart'] },
  { icon: '💕', name: 'two hearts', keywords: ['love', 'heart'] },
  { icon: '💟', name: 'heart decoration', keywords: ['love', 'heart'] },
  { icon: '❣️', name: 'exclamation heart', keywords: ['love', 'heart'] },
  { icon: '💔', name: 'broken heart', keywords: ['broken', 'sad'] },
  { icon: '❤️', name: 'red heart', keywords: ['love', 'heart'] },
  { icon: '🧡', name: 'orange heart', keywords: ['love', 'heart'] },
  { icon: '💛', name: 'yellow heart', keywords: ['love', 'heart'] },
  { icon: '💚', name: 'green heart', keywords: ['love', 'heart'] },
  { icon: '💙', name: 'blue heart', keywords: ['love', 'heart'] },
  { icon: '💜', name: 'purple heart', keywords: ['love', 'heart'] },
  { icon: '🖤', name: 'black heart', keywords: ['love', 'heart'] },
  { icon: '🤍', name: 'white heart', keywords: ['love', 'heart'] },
  { icon: '🤎', name: 'brown heart', keywords: ['love', 'heart'] },
  { icon: '💯', name: 'hundred points', keywords: ['100', 'perfect'] },
  { icon: '💢', name: 'anger symbol', keywords: ['angry', 'mad'] },
  { icon: '💥', name: 'collision', keywords: ['boom', 'explosion'] },
  { icon: '💫', name: 'dizzy', keywords: ['dizzy', 'star'] },
  { icon: '💦', name: 'sweat droplets', keywords: ['sweat', 'water'] },
  { icon: '💨', name: 'dashing away', keywords: ['wind', 'speed'] },
  { icon: '🕳️', name: 'hole', keywords: ['hole', 'empty'] },
  { icon: '💣', name: 'bomb', keywords: ['bomb', 'explosion'] },
  { icon: '💬', name: 'speech balloon', keywords: ['talk', 'chat'] },
  { icon: '👁️‍🗨️', name: 'eye in speech bubble', keywords: ['eye', 'see'] },
  { icon: '🗨️', name: 'left speech bubble', keywords: ['talk', 'chat'] },
  { icon: '🗯️', name: 'right anger bubble', keywords: ['angry', 'shout'] },
  { icon: '💭', name: 'thought balloon', keywords: ['think', 'idea'] },
  { icon: '💤', name: 'zzz', keywords: ['sleep', 'tired'] },
  { icon: '👍', name: 'thumbs up', keywords: ['good', 'ok', 'yes'] },
  { icon: '👎', name: 'thumbs down', keywords: ['bad', 'no'] },
  { icon: '👌', name: 'OK hand', keywords: ['ok', 'yes'] },
  { icon: '✌️', name: 'victory hand', keywords: ['peace', 'victory'] },
  { icon: '🤞', name: 'crossed fingers', keywords: ['luck', 'hope'] },
  { icon: '🤟', name: 'love-you gesture', keywords: ['love', 'heart'] },
  { icon: '🤘', name: 'sign of the horns', keywords: ['rock', 'metal'] },
  { icon: '🤙', name: 'call me hand', keywords: ['call', 'phone'] },
  { icon: '👈', name: 'backhand index pointing left', keywords: ['left', 'point'] },
  { icon: '👉', name: 'backhand index pointing right', keywords: ['right', 'point'] },
  { icon: '👆', name: 'backhand index pointing up', keywords: ['up', 'point'] },
  { icon: '👇', name: 'backhand index pointing down', keywords: ['down', 'point'] },
  { icon: '☝️', name: 'index pointing up', keywords: ['up', 'point'] },
  { icon: '✋', name: 'raised hand', keywords: ['stop', 'hand'] },
  { icon: '🤚', name: 'raised back of hand', keywords: ['stop', 'back'] },
  { icon: '🖐️', name: 'hand with fingers splayed', keywords: ['hand', 'five'] },
  { icon: '🖖', name: 'vulcan salute', keywords: ['star trek', 'spock'] },
  { icon: '👋', name: 'waving hand', keywords: ['wave', 'hello', 'goodbye'] },
  { icon: '🤏', name: 'pinching hand', keywords: ['small', 'pinch'] },
  { icon: '✊', name: 'raised fist', keywords: ['fist', 'power'] },
  { icon: '👊', name: 'oncoming fist', keywords: ['fist', 'punch'] },
  { icon: '🤛', name: 'left-facing fist', keywords: ['fist', 'left'] },
  { icon: '🤜', name: 'right-facing fist', keywords: ['fist', 'right'] },
  { icon: '👏', name: 'clapping hands', keywords: ['clap', 'applause'] },
  { icon: '🙌', name: 'raising hands', keywords: ['praise', 'celebration'] },
  { icon: '👐', name: 'open hands', keywords: ['open', 'hug'] },
  { icon: '🤲', name: 'palms up together', keywords: ['open', 'pray'] },
  { icon: '🤝', name: 'handshake', keywords: ['agreement', 'deal'] },
  { icon: '🙏', name: 'folded hands', keywords: ['please', 'thank you', 'pray'] },
  { icon: '✍️', name: 'writing hand', keywords: ['write', 'sign'] },
  { icon: '💅', name: 'nail polish', keywords: ['beauty', 'care'] },
  { icon: '🤳', name: 'selfie', keywords: ['photo', 'selfie'] },
  { icon: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle'] },
  { icon: '🦾', name: 'mechanical arm', keywords: ['robot', 'cyborg'] },
  { icon: '🦿', name: 'mechanical leg', keywords: ['robot', 'cyborg'] },
  { icon: '🦵', name: 'leg', keywords: ['leg', 'kick'] },
  { icon: '🦶', name: 'foot', keywords: ['foot', 'kick'] },
  { icon: '👂', name: 'ear', keywords: ['hear', 'listen'] },
  { icon: '🦻', name: 'ear with hearing aid', keywords: ['hear', 'hearing'] },
  { icon: '👃', name: 'nose', keywords: ['nose', 'smell'] },
  { icon: '🧠', name: 'brain', keywords: ['brain', 'think'] },
  { icon: '🫀', name: 'anatomical heart', keywords: ['heart', 'organ'] },
  { icon: '🫁', name: 'lungs', keywords: ['lungs', 'breath'] },
  { icon: '🦷', name: 'tooth', keywords: ['tooth', 'dentist'] },
  { icon: '🦴', name: 'bone', keywords: ['bone', 'skeleton'] },
  { icon: '👀', name: 'eyes', keywords: ['eyes', 'see'] },
  { icon: '👁️', name: 'eye', keywords: ['eye', 'see'] },
  { icon: '👅', name: 'tongue', keywords: ['tongue', 'taste'] },
  { icon: '👄', name: 'mouth', keywords: ['mouth', 'talk'] },
  { icon: '👶', name: 'baby', keywords: ['baby', 'child'] },
  { icon: '🧒', name: 'child', keywords: ['child', 'kid'] },
  { icon: '👦', name: 'boy', keywords: ['boy', 'male'] },
  { icon: '👧', name: 'girl', keywords: ['girl', 'female'] },
  { icon: '🧑', name: 'person', keywords: ['person', 'human'] },
  { icon: '👱', name: 'person with blond hair', keywords: ['blond', 'hair'] },
  { icon: '👨', name: 'man', keywords: ['man', 'male'] },
  { icon: '🧔', name: 'man with beard', keywords: ['beard', 'man'] },
  { icon: '👩', name: 'woman', keywords: ['woman', 'female'] },
  { icon: '🧓', name: 'older person', keywords: ['old', 'elderly'] },
  { icon: '👴', name: 'old man', keywords: ['old', 'man'] },
  { icon: '👵', name: 'old woman', keywords: ['old', 'woman'] },
  { icon: '🙍', name: 'person frowning', keywords: ['frown', 'disappointed'] },
  { icon: '🙍‍♂️', name: 'man frowning', keywords: ['frown', 'man'] },
  { icon: '🙍‍♀️', name: 'woman frowning', keywords: ['frown', 'woman'] },
  { icon: '🙎', name: 'person pouting', keywords: ['pout', 'angry'] },
  { icon: '🙎‍♂️', name: 'man pouting', keywords: ['pout', 'man'] },
  { icon: '🙎‍♀️', name: 'woman pouting', keywords: ['pout', 'woman'] },
  { icon: '🙅', name: 'person gesturing NO', keywords: ['no', 'prohibit'] },
  { icon: '🙅‍♂️', name: 'man gesturing NO', keywords: ['no', 'man'] },
  { icon: '🙅‍♀️', name: 'woman gesturing NO', keywords: ['no', 'woman'] },
  { icon: '🙆', name: 'person gesturing OK', keywords: ['ok', 'approve'] },
  { icon: '🙆‍♂️', name: 'man gesturing OK', keywords: ['ok', 'man'] },
  { icon: '🙆‍♀️', name: 'woman gesturing OK', keywords: ['ok', 'woman'] },
  { icon: '💁', name: 'person tipping hand', keywords: ['help', 'information'] },
  { icon: '💁‍♂️', name: 'man tipping hand', keywords: ['help', 'man'] },
  { icon: '💁‍♀️', name: 'woman tipping hand', keywords: ['help', 'woman'] },
  { icon: '🙋', name: 'person raising hand', keywords: ['question', 'ask'] },
  { icon: '🙋‍♂️', name: 'man raising hand', keywords: ['question', 'man'] },
  { icon: '🙋‍♀️', name: 'woman raising hand', keywords: ['question', 'woman'] },
  { icon: '🧏', name: 'deaf person', keywords: ['deaf', 'hear'] },
  { icon: '🧏‍♂️', name: 'deaf man', keywords: ['deaf', 'man'] },
  { icon: '🧏‍♀️', name: 'deaf woman', keywords: ['deaf', 'woman'] },
  { icon: '🙇', name: 'person bowing', keywords: ['bow', 'respect'] },
  { icon: '🙇‍♂️', name: 'man bowing', keywords: ['bow', 'man'] },
  { icon: '🙇‍♀️', name: 'woman bowing', keywords: ['bow', 'woman'] },
  { icon: '🤦', name: 'face palm', keywords: ['frustration', 'disbelief'] },
  { icon: '🤦‍♂️', name: 'man facepalming', keywords: ['frustration', 'man'] },
  { icon: '🤦‍♀️', name: 'woman facepalming', keywords: ['frustration', 'woman'] },
  { icon: '🤷', name: 'person shrugging', keywords: ['shrug', 'confused'] },
  { icon: '🤷‍♂️', name: 'man shrugging', keywords: ['shrug', 'man'] },
  { icon: '🤷‍♀️', name: 'woman shrugging', keywords: ['shrug', 'woman'] },
  { icon: '🧑‍⚕️', name: 'health worker', keywords: ['doctor', 'nurse', 'health'] },
  { icon: '👨‍⚕️', name: 'man health worker', keywords: ['doctor', 'man'] },
  { icon: '👩‍⚕️', name: 'woman health worker', keywords: ['doctor', 'woman'] },
  { icon: '🧑‍🎓', name: 'student', keywords: ['student', 'graduation'] },
  { icon: '👨‍🎓', name: 'man student', keywords: ['student', 'man'] },
  { icon: '👩‍🎓', name: 'woman student', keywords: ['student', 'woman'] },
  { icon: '🧑‍🏫', name: 'teacher', keywords: ['teacher', 'education'] },
  { icon: '👨‍🏫', name: 'man teacher', keywords: ['teacher', 'man'] },
  { icon: '👩‍🏫', name: 'woman teacher', keywords: ['teacher', 'woman'] },
  { icon: '🧑‍⚖️', name: 'judge', keywords: ['judge', 'law'] },
  { icon: '👨‍⚖️', name: 'man judge', keywords: ['judge', 'man'] },
  { icon: '👩‍⚖️', name: 'woman judge', keywords: ['judge', 'woman'] },
  { icon: '🧑‍🌾', name: 'farmer', keywords: ['farmer', 'agriculture'] },
  { icon: '👨‍🌾', name: 'man farmer', keywords: ['farmer', 'man'] },
  { icon: '👩‍🌾', name: 'woman farmer', keywords: ['farmer', 'woman'] },
  { icon: '🧑‍🍳', name: 'cook', keywords: ['cook', 'chef'] },
  { icon: '👨‍🍳', name: 'man cook', keywords: ['cook', 'man'] },
  { icon: '👩‍🍳', name: 'woman cook', keywords: ['cook', 'woman'] },
  { icon: '🧑‍🔧', name: 'mechanic', keywords: ['mechanic', 'repair'] },
  { icon: '👨‍🔧', name: 'man mechanic', keywords: ['mechanic', 'man'] },
  { icon: '👩‍🔧', name: 'woman mechanic', keywords: ['mechanic', 'woman'] },
  { icon: '🧑‍🏭', name: 'factory worker', keywords: ['factory', 'worker'] },
  { icon: '👨‍🏭', name: 'man factory worker', keywords: ['factory', 'man'] },
  { icon: '👩‍🏭', name: 'woman factory worker', keywords: ['factory', 'woman'] },
  { icon: '🧑‍💼', name: 'office worker', keywords: ['office', 'worker'] },
  { icon: '👨‍💼', name: 'man office worker', keywords: ['office', 'man'] },
  { icon: '👩‍💼', name: 'woman office worker', keywords: ['office', 'woman'] },
  { icon: '🧑‍🔬', name: 'scientist', keywords: ['scientist', 'lab'] },
  { icon: '👨‍🔬', name: 'man scientist', keywords: ['scientist', 'man'] },
  { icon: '👩‍🔬', name: 'woman scientist', keywords: ['scientist', 'woman'] },
  { icon: '🧑‍💻', name: 'technologist', keywords: ['technologist', 'computer'] },
  { icon: '👨‍💻', name: 'man technologist', keywords: ['technologist', 'man'] },
  { icon: '👩‍💻', name: 'woman technologist', keywords: ['technologist', 'woman'] },
  { icon: '🧑‍🎤', name: 'singer', keywords: ['singer', 'music'] },
  { icon: '👨‍🎤', name: 'man singer', keywords: ['singer', 'man'] },
  { icon: '👩‍🎤', name: 'woman singer', keywords: ['singer', 'woman'] },
  { icon: '🧑‍🎨', name: 'artist', keywords: ['artist', 'paint'] },
  { icon: '👨‍🎨', name: 'man artist', keywords: ['artist', 'man'] },
  { icon: '👩‍🎨', name: 'woman artist', keywords: ['artist', 'woman'] },
  { icon: '🧑‍✈️', name: 'pilot', keywords: ['pilot', 'plane'] },
  { icon: '👨‍✈️', name: 'man pilot', keywords: ['pilot', 'man'] },
  { icon: '👩‍✈️', name: 'woman pilot', keywords: ['pilot', 'woman'] },
  { icon: '🧑‍🚀', name: 'astronaut', keywords: ['astronaut', 'space'] },
  { icon: '👨‍🚀', name: 'man astronaut', keywords: ['astronaut', 'man'] },
  { icon: '👩‍🚀', name: 'woman astronaut', keywords: ['astronaut', 'woman'] },
  { icon: '🧑‍⚖️', name: 'judge', keywords: ['judge', 'law'] },
  { icon: '👨‍⚖️', name: 'man judge', keywords: ['judge', 'man'] },
  { icon: '👩‍⚖️', name: 'woman judge', keywords: ['judge', 'woman'] },
  { icon: '🤝', name: 'handshake', keywords: ['agreement', 'deal'] },
  { icon: '🫂', name: 'people hugging', keywords: ['hug', 'love'] },
  { icon: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle'] },
  { icon: '🦵', name: 'leg', keywords: ['leg', 'kick'] },
  { icon: '🦶', name: 'foot', keywords: ['foot', 'kick'] },
  { icon: '👂', name: 'ear', keywords: ['hear', 'listen'] },
  { icon: '👃', name: 'nose', keywords: ['nose', 'smell'] },
  { icon: '🧠', name: 'brain', keywords: ['brain', 'think'] },
  { icon: '🫀', name: 'anatomical heart', keywords: ['heart', 'organ'] },
  { icon: '🫁', name: 'lungs', keywords: ['lungs', 'breath'] },
  { icon: '🦷', name: 'tooth', keywords: ['tooth', 'dentist'] },
  { icon: '🦴', name: 'bone', keywords: ['bone', 'skeleton'] },
  { icon: '👀', name: 'eyes', keywords: ['eyes', 'see'] },
  { icon: '👁️', name: 'eye', keywords: ['eye', 'see'] },
  { icon: '👅', name: 'tongue', keywords: ['tongue', 'taste'] },
  { icon: '👄', name: 'mouth', keywords: ['mouth', 'talk'] }
]